### ISSUE TITLE
VSCode extension constantly displays the terminal window with errors in it while typing

### ISSUE THREAD

**Issue by lukaszcz** [anoma/vscode-juvix#77] opened 2023-05-15 15:21 UTC
This is very annoying. Before you finish typing, there will be lots of distracting spurious error messages. Errors should only be underlined. Error message should only be displayed when one hovers over the underlined part.

**Comment by jonaprieto** [comment] 2023-05-15 17:35
Agree, @vrom911 is investigating a proper solution to this and other related issues.
In the meantime, I just pushed a temporary solution in v0.1.38.
- 7ca1c8e33eacf514d470c7f7e789c7d689bcfc05

**Comment by jonaprieto** [comment] 2023-05-24 21:31
I'm closing this issue as I cannot reproduce it with the current 0.1.34 version.
For reference, it seems it was closed by 

- #81

**Closed by jonaprieto** 2023-05-24 21:31 UTC
Labels: bug
